"""remove wechat legacy openid columns

Revision ID: 1debf5a3152b
Revises: c25ed34e188e
Create Date: 2026-08-09 16:49:50.968540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1debf5a3152b'
down_revision: Union[str, Sequence[str], None] = 'c25ed34e188e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'openid')
    op.alter_column('user_login_log', 'login_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='登录方式 account(账号密码)',
               existing_comment='登录方式 wechat/phone',
               existing_nullable=False)
    op.alter_column('user_login_log', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               comment='手机号(预留,当前账号制未使用)',
               existing_comment='手机号(微信登录时为空)',
               existing_nullable=True)
    op.drop_column('user_login_log', 'openid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_log', sa.Column('openid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='微信openid(手机号登录时为空)'))
    op.alter_column('user_login_log', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               comment='手机号(微信登录时为空)',
               existing_comment='手机号(预留,当前账号制未使用)',
               existing_nullable=True)
    op.alter_column('user_login_log', 'login_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='登录方式 wechat/phone',
               existing_comment='登录方式 account(账号密码)',
               existing_nullable=False)
    op.add_column('user', sa.Column('openid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='微信用户唯一标识(历史字段,已不使用)'))
    # ### end Alembic commands ###
