"""login logs tables and employee force_change_password

Revision ID: 6bcbdde53b35
Revises: 7ed80d8f6e97
Create Date: 2026-08-09 16:03:24.298613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcbdde53b35'
down_revision: Union[str, Sequence[str], None] = '7ed80d8f6e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_login_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('emp_id', sa.BigInteger(), nullable=True, comment='员工id(登录失败时可能为空)'),
    sa.Column('username', sa.String(length=32), nullable=False, comment='登录用户名'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1成功 0失败'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='浏览器UA'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='管理端登录日志'
    )
    op.create_table('user_login_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户id(登录失败时可能为空)'),
    sa.Column('login_type', sa.String(length=20), nullable=False, comment='登录方式 wechat/phone'),
    sa.Column('openid', sa.String(length=45), nullable=True, comment='微信openid(手机号登录时为空)'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号(微信登录时为空)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1成功 0失败'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='浏览器UA'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户端登录日志'
    )
    # server_default:已有员工行填充 0,避免 NOT NULL 无默认值导致 ALTER 失败
    op.add_column('employee', sa.Column('force_change_password', sa.Integer(), nullable=False, server_default='0', comment='首次登录是否强制改密 0否 1是'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'force_change_password')
    op.drop_table('user_login_log')
    op.drop_table('employee_login_log')
    # ### end Alembic commands ###
