"""user phone unique

Revision ID: 7d7385cd1e8d
Revises: 1debf5a3152b
Create Date: 2026-08-09 17:08:24.560201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d7385cd1e8d'
down_revision: Union[str, Sequence[str], None] = '1debf5a3152b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=11),
               comment='手机号(注册必填,用于找回密码/安全验证)',
               existing_comment='手机号',
               existing_nullable=True)
    op.create_unique_constraint('uk_user_phone', 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_user_phone', 'user', type_='unique')
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=11),
               comment='手机号',
               existing_comment='手机号(注册必填,用于找回密码/安全验证)',
               existing_nullable=True)
    # ### end Alembic commands ###
