"""status columns tinyint to int

Revision ID: a02ae5010d08
Revises: 6bcc11d23270
Create Date: 2026-08-06 15:22:25.158390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a02ae5010d08'
down_revision: Union[str, Sequence[str], None] = '6bcc11d23270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_book', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_comment='默认 0 否 1是',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'pay_status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='支付状态 0未支付 1已支付 2退款',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'delivery_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_comment='配送状态  1立即送出  0选择具体时间',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('orders', 'tableware_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_comment='餐具数量状态  1按餐量提供  0选择具体数量',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('shop_status', 'id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('shop_status', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='1营业 0打烊',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_status', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='1营业 0打烊',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('shop_status', 'id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('orders', 'tableware_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='餐具数量状态  1按餐量提供  0选择具体数量',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('orders', 'delivery_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='配送状态  1立即送出  0选择具体时间',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('orders', 'pay_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='支付状态 0未支付 1已支付 2退款',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('address_book', 'is_default',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='默认 0 否 1是',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
