"""user add username password

Revision ID: c25ed34e188e
Revises: 6bcbdde53b35
Create Date: 2026-08-09 16:28:24.660891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c25ed34e188e'
down_revision: Union[str, Sequence[str], None] = '6bcbdde53b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=True, comment='登录用户名'))
    op.add_column('user', sa.Column('password', sa.String(length=64), nullable=True, comment='密码(bcrypt)'))
    op.alter_column('user', 'openid',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=45),
               comment='微信用户唯一标识(历史字段,已不使用)',
               existing_comment='微信用户唯一标识',
               existing_nullable=True)
    op.create_unique_constraint('uk_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_user_username', 'user', type_='unique')
    op.alter_column('user', 'openid',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=45),
               comment='微信用户唯一标识',
               existing_comment='微信用户唯一标识(历史字段,已不使用)',
               existing_nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
